"use client";

import { motion } from "framer-motion";
import { useMemo, useState } from "react";
import type { DashboardData, EvidenceJob, Skill } from "@/lib/types";

const stages = ["Raw job sources", "Canonical schema", "Role mapping", "Skill extraction", "SQL aggregates", "Skill terrain", "Evidence trail", "Skill gap case"];
const categories = ["Programming", "Data / BI", "ML / AI", "Cloud / Engineering", "Collaboration"];

function Label({ children }: { children: React.ReactNode }) { return <p className="label">{children}</p>; }
function Section({ id, children }: { id: string; children: React.ReactNode }) { return <section id={id} className="section">{children}</section>; }
function Evidence({ job }: { job: EvidenceJob }) { return <article className="evidence"><p>{job.posted_at || "UNDATED"} · {job.location || "LOCATION NOT DISCLOSED"}</p><h3>{job.title}</h3><span>{job.company || "EMPLOYER NOT DISCLOSED"}</span><div>{job.roles.split(" | ").map((role) => <i key={role}>{role}</i>)}</div></article>; }

function SystemDiagram() {
  const [selected, setSelected] = useState(0);
  return <Section id="system"><div className="section-heading"><Label>01 / SYSTEM DIAGRAM</Label><h2>Evidence becomes a labor-market signal through a visible chain of transformations.</h2></div><div className="system"><div className="system-map">{stages.map((stage, index) => <motion.button key={stage} onClick={() => setSelected(index)} className={selected === index ? "system-node active" : "system-node"} whileTap={{ scale: 0.97 }}><b>{String(index + 1).padStart(2, "0")}</b><span>{stage}</span></motion.button>)}</div><aside className="system-inspector"><Label>ACTIVE LAYER / {String(selected + 1).padStart(2, "0")}</Label><h3>{stages[selected]}</h3><p>{["A bounded public or user-provided CSV is retained locally.", "Input fields normalize into an explicit, inspectable posting record.", "Title rules map postings to transparent role lenses.", "A regex dictionary captures explicitly stated skills only.", "SQLite makes each role and skill count reproducible.", "Role–skill intersections show where requirements co-occur.", "Source rows remain available beside each conclusion.", "Exact input labels are compared without career recommendations."][selected]}</p><small>STATIC ARTIFACT · PYTHON PIPELINE</small></aside></div></Section>;
}

function RoleDossiers({ data }: { data: DashboardData }) { const [open, setOpen] = useState<string | null>(null); return <Section id="roles"><div className="section-heading split"><div><Label>03 / ROLE DOSSIERS</Label><h2>Six lenses. One evidence base.</h2></div><p>Open a role to inspect the observed toolchain and its retained posting records.</p></div><div className="roles">{data.overview.role_comparison.map((role) => { const skills = data.roleSkills.roles[role.role] ?? []; const jobs = data.evidence.jobs.filter((job) => job.roles.includes(role.role)); return <article key={role.role} className={open === role.role ? "role open" : "role"}><button onClick={() => setOpen(open === role.role ? null : role.role)}><span>{role.role}</span><b>{role.posting_count} records</b><i>+</i></button><div className="role-body"><p>{skills.slice(0, 5).map((skill) => skill.skill).join(" · ") || "No extracted skills"}</p><div>{jobs.slice(0, 2).map((job) => <Evidence key={job.job_id} job={job} />)}</div></div></article>; })}</div></Section>; }

function Terrain({ data }: { data: DashboardData }) { const [skill, setSkill] = useState(data.overview.top_skills[0]?.skill ?? ""); const roles = Object.entries(data.roleSkills.roles); return <Section id="terrain"><div className="section-heading split"><div><Label>04 / SKILL TERRAIN</Label><h2>Skill presence is a relationship, not a bar chart.</h2></div><div className="category-strip">{categories.map((category) => <span key={category}>{category}</span>)}</div></div><div className="terrain"><div className="skill-list">{data.overview.top_skills.map((item) => <button key={item.skill} className={skill === item.skill ? "active" : ""} onClick={() => setSkill(item.skill)}>{item.skill}<small>{item.posting_count}</small></button>)}</div><div className="terrain-map"><Label>SELECTED SKILL / {skill}</Label>{roles.map(([role, items]) => { const found = items.find((item) => item.skill === skill); return <div key={role}><span>{role}</span><i className={found ? "linked" : ""} /><b>{found ? `${found.posting_count} explicit mentions` : "No dictionary match"}</b></div>; })}</div></div></Section>; }

function Ledger({ data }: { data: DashboardData }) { const [query, setQuery] = useState(""); const rows = data.evidence.jobs.filter((job) => `${job.title} ${job.company} ${job.location} ${job.roles}`.toLowerCase().includes(query.toLowerCase())); return <Section id="evidence"><div className="section-heading split"><div><Label>05 / EVIDENCE LEDGER</Label><h2>Every visible claim has a traceable posting record.</h2></div><label className="search">SEARCH EVIDENCE<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Role, company, location" /></label></div><div className="ledger">{rows.map((job) => <Evidence key={job.job_id} job={job} />)}{!rows.length && <p className="empty">No bundled evidence row matches that query.</p>}</div></Section>; }

function SkillGap({ data }: { data: DashboardData }) { const [role, setRole] = useState(Object.keys(data.roleSkills.roles)[0] ?? ""); const [entry, setEntry] = useState(""); const wanted = data.roleSkills.roles[role] ?? []; const entered = useMemo(() => new Set(entry.toLowerCase().split(",").map((item) => item.trim()).filter(Boolean)), [entry]); const matched = wanted.filter((item) => entered.has(item.skill.toLowerCase())); const missing = wanted.filter((item) => !entered.has(item.skill.toLowerCase())); return <Section id="gap"><div className="gap"><div><Label>06 / SKILL GAP CASE</Label><h2>Compare named skills to observed requirements.</h2><p>Observed frequency, not career advice.</p></div><div className="gap-controls"><label>TARGET ROLE<select value={role} onChange={(event) => setRole(event.target.value)}>{Object.keys(data.roleSkills.roles).map((item) => <option key={item}>{item}</option>)}</select></label><label>YOUR CANONICAL SKILLS<input value={entry} onChange={(event) => setEntry(event.target.value)} placeholder="Python, SQL, Docker" /></label></div></div><div className="gap-result"><strong>{wanted.length ? Math.round((matched.length / wanted.length) * 100) : 0}%</strong><p>{matched.length} of {wanted.length} observed labels match exactly.</p><div><h3>Matched</h3>{matched.map((item) => <span key={item.skill}>{item.skill}</span>) || "—"}</div><div><h3>Frequently observed skills not matched by your input</h3>{missing.map((item) => <span key={item.skill}>{item.skill} <b>{item.posting_count}</b></span>)}</div></div></Section>; }

export function Dashboard({ data }: { data: DashboardData }) { return <main><nav className="site-nav"><a href="#top">WS / WORKSIGNAL</a><div><a href="#system">System</a><a href="#evidence">Evidence</a><a href="#method">Method</a></div></nav><Section id="top"><div className="hero"><div><Label>JOB-MARKET INTELLIGENCE WORKSPACE</Label><h1>Work<span>Signal</span></h1><h2>Job-market intelligence from reproducible posting evidence.</h2></div><div className="hero-copy"><p>A static, traceable intelligence layer for understanding role requirements, skill demand, and evidence-backed career signals.</p><div>{["Python pipeline", "SQL analysis", "Static JSON artifacts", "Vercel interface", "No paid API", "No live scraping"].map((item) => <span key={item}>{item}</span>)}</div></div></div></Section><SystemDiagram /><Section id="brief"><div className="brief"><div><Label>02 / MARKET SIGNAL BRIEF</Label><h2>{data.overview.kpis.top_observed_skill} is the most repeated explicit skill signal in this bounded sample.</h2><p>{data.overview.source.disclosure} Role counts may overlap where titles map to more than one role.</p></div><dl><div><dt>ROLE LENSES</dt><dd>{data.overview.kpis.roles_covered}</dd></div><div><dt>MAPPED POSTINGS</dt><dd>{data.overview.kpis.matched_postings}</dd></div><div><dt>SOURCE CONDITION</dt><dd>STATIC</dd></div></dl></div></Section><RoleDossiers data={data} /><Terrain data={data} /><Ledger data={data} /><SkillGap data={data} /><Section id="method"><div className="method"><div><Label>07 / METHOD DOSSIER</Label><h2>Built to show the boundary of the evidence, not hide it.</h2></div><div>{["Source: bundled illustrative sample; a larger dataset is only accepted when license and redistribution terms are verified.", "Pipeline: cleaning, multi-label role mapping, regex skill extraction, SQLite aggregation, and exploratory clustering occur in Python.", "Limitations: static small sample, finite dictionary, no live scraping, no paid APIs, and no career advice."].map((item, index) => <p key={item}><b>0{index + 1}</b>{item}</p>)}</div></div></Section><footer><span>WORKSIGNAL / STATIC LABOR-MARKET EVIDENCE</span><a href="https://github.com/RicoMitra/indonesia-job-market-skill-analyzer">VIEW REPOSITORY ↗</a></footer></main>; }
